spring:
  threads:
    virtual:
      enabled: true
  session:
    redis:
      namespace: ${REDIS_NAMESPACE}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      repositories:
        enabled: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      read-only: true

server:
  servlet:
    session:
      cookie:
        max-age: 30d

kakao:
  clientId: ${KAKAO_CLIENT_ID}
  clientSecret: ${KAKAO_CLIENT_SECRET}
  redirectUri: ${KAKAO_REDIRECT_URI}

springdoc:
  packagesToScan: com.peacock.api

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true

#logging:
#  level:
#    org.jooq.tools.LoggerListener: DEBUG
